"""relation

Revision ID: 18eabe23176d
Revises: c6dc67d47000
Create Date: 2023-02-03 14:40:37.987089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18eabe23176d'
down_revision = 'c6dc67d47000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'building', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'food_routine', 'building', ['building'], ['id'])
    op.add_column('tenant', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tenant', 'users', ['user_id'], ['id'])
    op.drop_column('tenant', 'user')
    op.add_column('token', sa.Column('type', sa.String(length=500), nullable=False))
    op.create_foreign_key(None, 'transaction', 'building', ['building'], ['id'])
    op.create_foreign_key(None, 'transaction', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('token', 'type')
    op.add_column('tenant', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant', type_='foreignkey')
    op.drop_column('tenant', 'user_id')
    op.drop_constraint(None, 'food_routine', type_='foreignkey')
    op.drop_constraint(None, 'building', type_='foreignkey')
    op.drop_column('building', 'user_id')
    # ### end Alembic commands ###
