"""user update lendth

Revision ID: c6dc67d47000
Revises: 78e0297c7901
Create Date: 2023-02-03 13:00:57.298266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dc67d47000'
down_revision = '78e0297c7901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verifed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.drop_column('users', 'verifed')
    # ### end Alembic commands ###
