"""new table add

Revision ID: f38cd924c823
Revises: 
Create Date: 2023-02-01 13:54:39.142733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38cd924c823'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TENANT', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('single_bed', sa.Integer(), nullable=True),
    sa.Column('double_bed', sa.Integer(), nullable=True),
    sa.Column('three_bed', sa.Integer(), nullable=True),
    sa.Column('four_bed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=False),
    sa.Column('lunch_time', sa.DateTime(), nullable=True),
    sa.Column('break_fast_time', sa.DateTime(), nullable=True),
    sa.Column('snack_time', sa.DateTime(), nullable=True),
    sa.Column('dinner_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_routine')
    op.drop_table('tenant')
    op.drop_table('building')
    op.drop_table('users')
    # ### end Alembic commands ###
